# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alta_productos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Agrega_Prod(object):
    def setupUi(self, Agrega_Prod):
        Agrega_Prod.setObjectName("Agrega_Prod")
        Agrega_Prod.resize(382, 201)
        self.gridLayout_2 = QtWidgets.QGridLayout(Agrega_Prod)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lb_Tit = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lb_Tit.setFont(font)
        self.lb_Tit.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Tit.setObjectName("lb_Tit")
        self.gridLayout.addWidget(self.lb_Tit, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lb_art = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_art.setFont(font)
        self.lb_art.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_art.setObjectName("lb_art")
        self.gridLayout.addWidget(self.lb_art, 1, 1, 1, 1)
        self.ln_Art = QtWidgets.QLineEdit(Agrega_Prod)
        self.ln_Art.setObjectName("ln_Art")
        self.gridLayout.addWidget(self.ln_Art, 1, 2, 1, 1)
        self.pb_Guardar = QtWidgets.QPushButton(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Guardar.setFont(font)
        self.pb_Guardar.setObjectName("pb_Guardar")
        self.gridLayout.addWidget(self.pb_Guardar, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.lb_Desc = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_Desc.setFont(font)
        self.lb_Desc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Desc.setObjectName("lb_Desc")
        self.gridLayout.addWidget(self.lb_Desc, 2, 1, 1, 1)
        self.ln_Desc = QtWidgets.QLineEdit(Agrega_Prod)
        self.ln_Desc.setObjectName("ln_Desc")
        self.gridLayout.addWidget(self.ln_Desc, 2, 2, 1, 1)
        self.pb_Salir = QtWidgets.QPushButton(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_Salir.setFont(font)
        self.pb_Salir.setObjectName("pb_Salir")
        self.gridLayout.addWidget(self.pb_Salir, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.lb_Peso = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_Peso.setFont(font)
        self.lb_Peso.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Peso.setObjectName("lb_Peso")
        self.gridLayout.addWidget(self.lb_Peso, 3, 1, 1, 1)
        self.ln_Peso = QtWidgets.QLineEdit(Agrega_Prod)
        self.ln_Peso.setObjectName("ln_Peso")
        self.gridLayout.addWidget(self.ln_Peso, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        self.lb_Cant = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_Cant.setFont(font)
        self.lb_Cant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Cant.setObjectName("lb_Cant")
        self.gridLayout.addWidget(self.lb_Cant, 4, 1, 1, 1)
        self.ln_Cant = QtWidgets.QLineEdit(Agrega_Prod)
        self.ln_Cant.setObjectName("ln_Cant")
        self.gridLayout.addWidget(self.ln_Cant, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        self.lb_Peso_Unit = QtWidgets.QLabel(Agrega_Prod)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lb_Precio_Unit.setFont(font)
        self.lb_Precio_Unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Precio_Unit.setObjectName("lb_Peso_Unit")
        self.gridLayout.addWidget(self.lb_Peso_Unit, 5, 1, 1, 1)
        self.ln_Precio_Unit = QtWidgets.QLineEdit(Agrega_Prod)
        self.ln_Precio_Unit.setObjectName("ln_Peso_Unit")
        self.gridLayout.addWidget(self.ln_Peso_Unit, 5, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Agrega_Prod)
        self.pb_Salir.pressed.connect(Agrega_Prod.close)
        QtCore.QMetaObject.connectSlotsByName(Agrega_Prod)

    def retranslateUi(self, Agrega_Prod):
        _translate = QtCore.QCoreApplication.translate
        Agrega_Prod.setWindowTitle(_translate("Agrega_Prod", "Alta de Productos"))
        self.lb_Tit.setText(_translate("Agrega_Prod", "Alta de Productos"))
        self.lb_art.setText(_translate("Agrega_Prod", "Artículo:"))
        self.pb_Guardar.setText(_translate("Agrega_Prod", "Guardar"))
        self.lb_Desc.setText(_translate("Agrega_Prod", "Descripción:"))
        self.pb_Salir.setText(_translate("Agrega_Prod", "Salir"))
        self.lb_Peso.setText(_translate("Agrega_Prod", "Peso:"))
        self.lb_Cant.setText(_translate("Agrega_Prod", "Cantidad:"))
        self.lb_Peso_Unit.setText(_translate("Agrega_Prod", "$ Unitaro:"))

